/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalmenu;

import java.awt.Color;

/**
 *
 * @author Titanium
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
        /* Altera cor da janela */
        this.getContentPane().setBackground(Color.LIGHT_GRAY);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jStart = new javax.swing.JButton();
        JInstructions = new javax.swing.JButton();
        jSair = new javax.swing.JButton();
        jCreditos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(null);

        jStart.setBackground(new java.awt.Color(255, 0, 0));
        jStart.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
        jStart.setForeground(new java.awt.Color(255, 255, 255));
        jStart.setText("Iniciar");
        jStart.setFocusPainted(false);
        jStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStartActionPerformed(evt);
            }
        });
        getContentPane().add(jStart);
        jStart.setBounds(330, 240, 96, 40);

        JInstructions.setBackground(new java.awt.Color(0, 255, 0));
        JInstructions.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
        JInstructions.setForeground(new java.awt.Color(255, 255, 255));
        JInstructions.setText("Instruções");
        JInstructions.setFocusPainted(false);
        JInstructions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JInstructionsActionPerformed(evt);
            }
        });
        getContentPane().add(JInstructions);
        JInstructions.setBounds(440, 240, 130, 40);

        jSair.setBackground(new java.awt.Color(0, 0, 255));
        jSair.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
        jSair.setForeground(new java.awt.Color(255, 255, 255));
        jSair.setText("Sair");
        jSair.setFocusPainted(false);
        jSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairActionPerformed(evt);
            }
        });
        getContentPane().add(jSair);
        jSair.setBounds(580, 240, 96, 40);

        jCreditos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCreditos.setText("por Adriano Belfort, Rodrigo Ferrari e Ilan Figueiredo");
        getContentPane().add(jCreditos);
        jCreditos.setBounds(356, 423, 283, 44);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adriano\\Documents\\NetBeansProjects\\Pong3D\\cg-2014\\data\\pong1000.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1, -4, 1000, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStartActionPerformed
        // chama ServerSettings
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ServerSettings janelaServer = new ServerSettings();
                janelaServer.setVisible(true);
                janelaServer.setLocationRelativeTo(null);
            }
        });
    }//GEN-LAST:event_jStartActionPerformed

    private void jSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairActionPerformed
        // Sair e fechar
        this.dispose();
    }//GEN-LAST:event_jSairActionPerformed

    private void JInstructionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JInstructionsActionPerformed
        // chama Intructions
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Instructions janelaInst = new Instructions();
                janelaInst.setVisible(true);
                janelaInst.setLocationRelativeTo(null);
            }
        });
    }//GEN-LAST:event_JInstructionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JInstructions;
    private javax.swing.JLabel jCreditos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jSair;
    private javax.swing.JButton jStart;
    // End of variables declaration//GEN-END:variables
}
