/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package menus;

/**
 *
 * @author Rodrigo
 */
public class initialMenu extends javax.swing.JFrame {

    /**
     * Creates new form initialMenu
     */
    public initialMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MultiplayerButton = new javax.swing.JButton();
        InstructionsButton = new javax.swing.JButton();
        OptionsButton = new javax.swing.JButton();
        CreditsButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SinglePlayerButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MultiplayerButton.setText("MultiPlayer");
        MultiplayerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MultiplayerButtonMouseReleased(evt);
            }
        });
        MultiplayerButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MultiplayerButtonKeyReleased(evt);
            }
        });

        InstructionsButton.setText("Instructions");
        InstructionsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                InstructionsButtonMouseReleased(evt);
            }
        });
        InstructionsButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                InstructionsButtonKeyReleased(evt);
            }
        });

        OptionsButton.setText("Options");
        OptionsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                OptionsButtonMouseReleased(evt);
            }
        });
        OptionsButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                OptionsButtonKeyReleased(evt);
            }
        });

        CreditsButton.setText("Credits");
        CreditsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CreditsButtonMouseReleased(evt);
            }
        });
        CreditsButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CreditsButtonKeyReleased(evt);
            }
        });

        ExitButton.setText("Exit");
        ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ExitButtonMouseReleased(evt);
            }
        });
        ExitButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ExitButtonKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Broadway Copyist Text Ext", 0, 36)); // NOI18N
        jLabel1.setText("Pong 3D");

        SinglePlayerButton.setText("Single Player");
        SinglePlayerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SinglePlayerButtonMouseReleased(evt);
            }
        });
        SinglePlayerButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SinglePlayerButtonKeyReleased(evt);
            }
        });

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SinglePlayerButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(MultiplayerButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(InstructionsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OptionsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CreditsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SinglePlayerButton)
                .addGap(18, 18, 18)
                .addComponent(MultiplayerButton)
                .addGap(18, 18, 18)
                .addComponent(InstructionsButton)
                .addGap(18, 18, 18)
                .addComponent(OptionsButton)
                .addGap(18, 18, 18)
                .addComponent(CreditsButton)
                .addGap(18, 18, 18)
                .addComponent(ExitButton)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MultiplayerButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MultiplayerButtonKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_MultiplayerButtonKeyReleased

    private void InstructionsButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InstructionsButtonKeyReleased
         
    }//GEN-LAST:event_InstructionsButtonKeyReleased

    private void OptionsButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OptionsButtonKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_OptionsButtonKeyReleased

    private void CreditsButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CreditsButtonKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_CreditsButtonKeyReleased

    private void ExitButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ExitButtonKeyReleased
        System.exit(0);
    }//GEN-LAST:event_ExitButtonKeyReleased

    private void SinglePlayerButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SinglePlayerButtonKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_SinglePlayerButtonKeyReleased

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed

    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void SinglePlayerButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SinglePlayerButtonMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_SinglePlayerButtonMouseReleased

    private void MultiplayerButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MultiplayerButtonMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_MultiplayerButtonMouseReleased

    private void InstructionsButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstructionsButtonMouseReleased
       java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                InstructionsDialog dialog = new InstructionsDialog(new javax.swing.JFrame(), true);
                dialog.setVisible(true);
            }
        });
    }//GEN-LAST:event_InstructionsButtonMouseReleased

    private void OptionsButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionsButtonMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_OptionsButtonMouseReleased

    private void CreditsButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreditsButtonMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_CreditsButtonMouseReleased

    private void ExitButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseReleased
        System.exit(0);
    }//GEN-LAST:event_ExitButtonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(initialMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(initialMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(initialMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(initialMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new initialMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreditsButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton InstructionsButton;
    private javax.swing.JButton MultiplayerButton;
    private javax.swing.JButton OptionsButton;
    private javax.swing.JButton SinglePlayerButton;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
